from esphome.components import sensor
import esphome.config_validation as cv
import esphome.codegen as cg
from esphome.const import (
    CONF_ID, CONF_TYPE,
    DEVICE_CLASS_POWER, DEVICE_CLASS_TEMPERATURE, DEVICE_CLASS_VOLTAGE,
    CONF_UNIT_OF_MEASUREMENT, UNIT_CELSIUS,
    CONF_ICON, ICON_THERMOMETER,
    CONF_ACCURACY_DECIMALS, CONF_DEVICE_CLASS,
    UNIT_WATT, UNIT_EMPTY, UNIT_VOLT, ICON_POWER,
)
from .. import truma_inetbox_ns, CONF_TRUMA_INETBOX_ID, TrumaINetBoxApp

DEPENDENCIES = ["truma_inetbox"]
CODEOWNERS = ["@Fabian-Schmidt"]

CONF_CLASS = "class"
TrumaSensor = truma_inetbox_ns.class_("TrumaSensor", sensor.Sensor, cg.Component)
TRUMA_SENSOR_TYPE_dummy_ns = truma_inetbox_ns.namespace("TRUMA_SENSOR_TYPE")

CONF_SUPPORTED_TYPE = {
    "CURRENT_ROOM_TEMPERATURE":  { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CURRENT_ROOM_TEMPERATURE,  CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 1, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "CURRENT_WATER_TEMPERATURE": { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CURRENT_WATER_TEMPERATURE, CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "TARGET_ROOM_TEMPERATURE":   { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TARGET_ROOM_TEMPERATURE,   CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "TARGET_WATER_TEMPERATURE":  { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TARGET_WATER_TEMPERATURE,  CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "HEATING_MODE":              { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.HEATING_MODE,              CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ACCURACY_DECIMALS: 0 },
    "ELECTRIC_POWER_LEVEL":      { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.ELECTRIC_POWER_LEVEL,      CONF_UNIT_OF_MEASUREMENT: UNIT_WATT,    CONF_ICON: ICON_POWER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_POWER },
    "ENERGY_MIX":                { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.ENERGY_MIX,                CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ACCURACY_DECIMALS: 0 },
    "OPERATING_STATUS":          { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.OPERATING_STATUS,          CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ACCURACY_DECIMALS: 0 },
    "HEATER_ERROR_CODE":         { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.HEATER_ERROR_CODE,         CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ACCURACY_DECIMALS: 0 },
    "TIMER_START_TIME":          { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TIMER_START_TIME,          CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:clock-start", CONF_ACCURACY_DECIMALS: 0 },
    "TIMER_STOP_TIME":           { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TIMER_STOP_TIME,           CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:clock-end",   CONF_ACCURACY_DECIMALS: 0 },
    "TIMER_ROOM_TEMPERATURE":    { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TIMER_ROOM_TEMPERATURE,    CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "TIMER_WATER_TEMPERATURE":   { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.TIMER_WATER_TEMPERATURE,   CONF_UNIT_OF_MEASUREMENT: UNIT_CELSIUS, CONF_ICON: ICON_THERMOMETER, CONF_ACCURACY_DECIMALS: 0, CONF_DEVICE_CLASS: DEVICE_CLASS_TEMPERATURE },
    "CLOCK_HOUR":                { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CLOCK_HOUR,                CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:clock-outline", CONF_ACCURACY_DECIMALS: 0 },
    "CLOCK_MINUTE":              { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CLOCK_MINUTE,              CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:clock-outline", CONF_ACCURACY_DECIMALS: 0 },
    "CP_PLUS_DISPLAY_STATUS":    { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CP_PLUS_DISPLAY_STATUS,    CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:television",    CONF_ACCURACY_DECIMALS: 0 },
    "HEATING_STATUS":            { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.HEATING_STATUS,            CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:water-boiler",  CONF_ACCURACY_DECIMALS: 0 },
    "HEATING_STATUS_2":          { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.HEATING_STATUS_2,          CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:water-boiler",  CONF_ACCURACY_DECIMALS: 0 },
    "CP_PLUS_VOLTAGE":           { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.CP_PLUS_VOLTAGE,           CONF_UNIT_OF_MEASUREMENT: UNIT_VOLT,    CONF_ICON: "mdi:flash",         CONF_ACCURACY_DECIMALS: 1, CONF_DEVICE_CLASS: DEVICE_CLASS_VOLTAGE },
    "VENT_MODE":                 { CONF_CLASS: TRUMA_SENSOR_TYPE_dummy_ns.VENT_MODE,                 CONF_UNIT_OF_MEASUREMENT: UNIT_EMPTY,   CONF_ICON: "mdi:fan",           CONF_ACCURACY_DECIMALS: 0 },
}


def set_default_based_on_type():
    def set_defaults_(config):
        t = CONF_SUPPORTED_TYPE[config[CONF_TYPE]]
        for key in [CONF_UNIT_OF_MEASUREMENT, CONF_ICON, CONF_ACCURACY_DECIMALS, CONF_DEVICE_CLASS]:
            if key in t and key not in config:
                config[key] = t[key]
        return config
    return set_defaults_


CONFIG_SCHEMA = sensor.sensor_schema().extend(cv.Schema({
    cv.GenerateID(): cv.declare_id(TrumaSensor),
    cv.GenerateID(CONF_TRUMA_INETBOX_ID): cv.use_id(TrumaINetBoxApp),
    cv.Required(CONF_TYPE): cv.enum(CONF_SUPPORTED_TYPE, upper=True),
})).extend(cv.COMPONENT_SCHEMA)

FINAL_VALIDATE_SCHEMA = set_default_based_on_type()


async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await sensor.register_sensor(var, config)
    await cg.register_parented(var, config[CONF_TRUMA_INETBOX_ID])
    cg.add(var.set_type(CONF_SUPPORTED_TYPE[config[CONF_TYPE]][CONF_CLASS]))
